language: python

python:
 - "2.7"

virtualenv:
      system_site_packages: true

services:
 - redis-server
 - mongodb

# command to install dependencies
install: 
 - "sudo apt-get install swig python-dev python-m2crypto redis-server"
 - "sudo python setup.py install"

script:
 - periscope/test/test.sh

notifications:
  slack: open-prog-net:kntQ6BsTfzplCztzIGIPgSdk
#  email:
#    on_success: never
#    on_failure: change
#    recipients:
#      - dlt@crest.iu.edu