language: python

python:
 - "2.7.9"

virtualenv:
      system_site_packages: true

services:
 - redis-server
 - mongodb

# command to install dependencies
install: 
 - "sudo apt-get install swig python-dev python-m2crypto redis-server"
 - "sudo python setup.py install"
 - "sudo mkdir /var/lib/periscope"
 - "sudo chown ${USER} /var/lib/periscope"

script:
 - periscope/test/test.sh

notifications:
  slack: crest-networks:nctOxrMsZdnYU8jGrkpSjpvf
#  email:
#    on_success: never
#    on_failure: change
#    recipients:
#      - dlt@crest.iu.edu