#!/bin/bash
#
# This script controls the periscoped service
#
# chkconfig: 2345 65 75
# description: Periscope is a measurement and topological store
#              for data logistics
#
# processname: periscoped

# source function library
. /etc/rc.d/init.d/functions

# source periscope configuration
if [ -f /etc/sysconfig/periscoped ]; then
   . /etc/sysconfig/periscoped
fi

lockfile=/var/lock/subsys/periscoped

RETVAL=0

start() {
    echo $"Starting monogodb: "
    service mongod start
    echo $"Starting redis: "
    service redis start
    echo -n $"Starting periscope: "
    supervisord -c /etc/supervisor/supervisor.conf
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo $"Stopping periscoped: "
    pkill supervisord
    echo $"Stopping redis: "
    service redis stop
    echo -n $"Stopping periscope: "
    service mongod stop
    [$RETVAL -eq 0 ] && rm -f $lockfile
    return $RETVAL
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart|force-reload|reload)
	restart
	;;
    condrestart)
	[ -f $lockfile ] && restart
	;;
    status)
	status periscoped
	RETVAL=$?
	;;
    *)
	echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
	exit 1
esac

exit $RETVAL
