#!/bin/bash
#
# This script controls the periscoped service
#
# chkconfig: 2345 65 75
# description: Periscope is a measurement and topological store
#              for data logistics
#
# processname: periscoped

# source function library
. /etc/rc.d/init.d/functions

# source periscoped configuration
if [ -f /etc/sysconfig/periscoped ]; then
   . /etc/sysconfig/periscoped
fi

lockfile=/var/lock/subsys/periscoped

RETVAL=0

start() {
    service mongod start
    service redis start
    service supervisord start
    echo -n $"Starting periscope: "
    timeout 2s supervisorctl start periscope-unis
    timeout 2s supervisorctl start periscope-ms
    RETVAL=$?
    echo "done"
    [ $RETVAL -eq 0 ] && touch $lockfile
    return $RETVAL
}

stop() {
    echo -n $"Stopping periscope: "
    timeout 2s supervisorctl stop periscope-unis
    timeout 2s supervisorctl stop periscope-ms
    echo "done"
    [ $RETVAL -eq 0 ] && rm -f $lockfile
    service redis stop
    service mongod stop
    return $RETVAL
}

restart() {
    stop
    sleep 1
    start
}

case "$1" in
    start)
	start
	;;
    stop)
	stop
	;;
    restart|force-reload|reload)
	restart
	;;
    condrestart)
	[ -f $lockfile ] && restart
	;;
    status)
	status periscope
	RETVAL=$?
	;;
    *)
	echo $"Usage: $0 {start|stop|status|restart|reload|force-reload|condrestart}"
	exit 1
esac

exit $RETVAL
